#!/usr/bin/env bash
#
# create_mod_template.sh — scaffold a new RimWorld-style entity mod.
#
# This is a path-agnostic version of create_mod.sh, intended to be copied
# out of this repo and used standalone (e.g. published alongside the
# StreetBum example mod). It does not assume any particular project layout
# and never touches engine source files.
#
# Usage:
#   ./create_mod_template.sh <ModName> [options]
#
# Options:
#   --output <dir>           Parent directory to create <ModName>/ in
#                             (default: ./Mods)
#   --author <Name>          Author string for mod.json (default: "Community")
#   --description <Text>     Description string for mod.json
#   --core                    Use modId "core.<mod_snake>" instead of "community.<mod_snake>"
#   -h, --help                Show this help
#
# What it generates (<output>/<ModName>/):
#   mod.json
#   Entities/<ModName>.json        - entityType, pawnLayers, propertySchemas, instances
#   Actions/<ModName>Actions.json  - DO_WANDER + FLEE_FROM_THREAT/ENGAGE_THREAT (shared)
#   Goals/<ModName>Goals.json       - WANDER (internal), FLEE (system), FIGHT (system)
#   Assets/Heads/                   - drop head sprites here (.png + .png.import)
#   Assets/Weapons/Ranged/           - drop ranged weapon sprites here
#   Assets/Names/names.json          - male/female name pools
#   README.md                        - modder-facing instructions
#
# No C# is generated and no engine source files are touched. The mod is fully
# data-driven: drop the resulting <ModName>/ folder into the game's Mods/
# directory and launch the game — no rebuild required.

set -euo pipefail

# -- Argument parsing ---------------------------------------------------------

OUTPUT_DIR="./Mods"
AUTHOR="Community"
DESCRIPTION=""
IS_CORE="false"

print_usage() {
    sed -n '2,28p' "$0" | sed 's/^# \{0,1\}//'
}

if [[ $# -eq 0 ]]; then
    print_usage
    exit 1
fi

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    print_usage
    exit 0
fi

MOD_NAME="$1"
shift

while [[ $# -gt 0 ]]; do
    case "$1" in
        --output)
            OUTPUT_DIR="$2"; shift 2 ;;
        --author)
            AUTHOR="$2"; shift 2 ;;
        --description)
            DESCRIPTION="$2"; shift 2 ;;
        --core)
            IS_CORE="true"; shift ;;
        -h|--help)
            print_usage; exit 0 ;;
        *)
            echo "Unknown option: $1" >&2
            print_usage
            exit 1 ;;
    esac
done

if [[ ! "$MOD_NAME" =~ ^[A-Z][A-Za-z0-9]*$ ]]; then
    echo "ERROR: <ModName> must be PascalCase (e.g. StreetBum), got: '$MOD_NAME'" >&2
    exit 1
fi

# PascalCase -> snake_case (StreetBum -> street_bum)
MOD_SNAKE="$(echo "$MOD_NAME" | sed -E 's/([a-z0-9])([A-Z])/\1_\2/g; s/([A-Z]+)([A-Z][a-z])/\1_\2/g' | tr '[:upper:]' '[:lower:]')"

if [[ "$IS_CORE" == "true" ]]; then
    MOD_ID="core.${MOD_SNAKE}"
else
    MOD_ID="community.${MOD_SNAKE}"
fi

if [[ -z "$DESCRIPTION" ]]; then
    DESCRIPTION="${MOD_NAME} - example mod (wandering NPC). Generated by create_mod_template.sh as a starting template for modders."
fi

MOD_DIR="${OUTPUT_DIR%/}/${MOD_NAME}"

if [[ -e "$MOD_DIR" ]]; then
    echo "ERROR: $MOD_DIR already exists - refusing to overwrite." >&2
    exit 1
fi

echo "Creating mod '${MOD_NAME}' (modId=${MOD_ID}) at ${MOD_DIR} ..."

mkdir -p \
    "$MOD_DIR/Entities" \
    "$MOD_DIR/Actions" \
    "$MOD_DIR/Goals" \
    "$MOD_DIR/Assets/Heads" \
    "$MOD_DIR/Assets/Weapons/Ranged" \
    "$MOD_DIR/Assets/Names"

# -- mod.json -----------------------------------------------------------------

cat > "$MOD_DIR/mod.json" <<EOF
{
    "modId": "${MOD_ID}",
    "name": "${MOD_NAME}",
    "version": "1.0.0",
    "author": "${AUTHOR}",
    "description": "${DESCRIPTION}",
    "isCoreContent": ${IS_CORE},
    "dependencies": [
        "core.base_systems"
    ],
    "priority": 100,
    "entities": [
        "Entities/${MOD_NAME}.json"
    ],
    "actions": [
        "Actions/${MOD_NAME}Actions.json"
    ],
    "goals": [
        "Goals/${MOD_NAME}Goals.json"
    ]
}
EOF

# -- Entities/<ModName>.json ---------------------------------------------------

cat > "$MOD_DIR/Entities/${MOD_NAME}.json" <<EOF
{
    "entityType": "${MOD_NAME}",
    "displayName": "${MOD_NAME}",
    "icon": "🧍",
    "color": [
        0.6,
        0.6,
        0.6
    ],
    "traitProfessions": [
        "Universal"
    ],
    "pawnLayers": {
        "headsRoot": "Assets/Heads",
        "weaponSpritesRoot": "Assets/Weapons/Ranged"
    },
    "namesRoot": "Assets/Names/names.json",
    "traitStartupCaps": {
        "CorePersonality": 50,
        "MoralEthical": 50
    },
    "propertySchemas": {
        "IsPlayerControlled": {
            "editable": "game",
            "type": "bool",
            "displayName": "Player Controlled",
            "category": "Control"
        },
        "FirstName": {
            "editable": "game",
            "type": "string",
            "displayName": "First Name",
            "category": "Identity"
        },
        "LastName": {
            "editable": "game",
            "type": "string",
            "displayName": "Last Name",
            "category": "Identity"
        },
        "Gender": {
            "editable": "game",
            "type": "enum",
            "values": [
                "Male",
                "Female",
                "Other"
            ],
            "displayName": "Gender",
            "category": "Identity"
        },
        "Age": {
            "editable": "game",
            "type": "int",
            "min": 18,
            "max": 75,
            "displayName": "Age",
            "category": "Identity"
        },
        "Health": {
            "editable": "game",
            "type": "int",
            "min": 0,
            "max": 100,
            "displayName": "Health",
            "category": "Status"
        },
        "Cash": {
            "editable": "game",
            "type": "float",
            "min": 0,
            "displayName": "Cash (\$)",
            "category": "Resources"
        },
        "IsAlive": {
            "editable": "game",
            "type": "bool",
            "displayName": "Alive",
            "category": "State"
        },
        "BehaviorType": {
            "editable": "game",
            "type": "string",
            "displayName": "Behavior Type",
            "category": "AI"
        },
        "IsWandering": {
            "editable": "game",
            "type": "bool",
            "displayName": "Is Wandering",
            "category": "AI"
        },
        "ThreatNearby": {
            "editable": "game",
            "type": "bool",
            "displayName": "Threat Nearby",
            "category": "Combat",
            "tooltip": "True when a hostile entity is within threat radius"
        },
        "ThreatEntityId": {
            "editable": "game",
            "type": "int",
            "displayName": "Threat Entity ID",
            "category": "Combat",
            "tooltip": "Entity ID of nearest hostile (-1 when none)"
        },
        "ThreatEliminated": {
            "editable": "game",
            "type": "bool",
            "displayName": "Threat Eliminated",
            "category": "Combat",
            "tooltip": "Set true when combat target is dead or fled"
        },
        "Safe": {
            "editable": "game",
            "type": "bool",
            "displayName": "Safe",
            "category": "Combat",
            "tooltip": "True when entity has fled far enough from the threat"
        },
        "DisplayHeight": {
            "editable": "never",
            "type": "int",
            "displayName": "Display Height",
            "category": "Internal"
        },
        "GoalPriorities": {
            "editable": "never",
            "type": "object",
            "displayName": "Goal Priorities",
            "category": "Internal",
            "tooltip": "Use goal table to edit priorities"
        },
        "ProximityRadius": {
            "editable": "game",
            "type": "float",
            "min": 0,
            "max": 500,
            "displayName": "Proximity Radius",
            "category": "Interaction"
        },
        "InteractionRules": {
            "editable": "never",
            "type": "array",
            "displayName": "Interaction Rules",
            "category": "Internal"
        }
    },
    "instances": [
        {
            "name": "Sample ${MOD_NAME} A",
            "type": "${MOD_NAME}",
            "x": 3000.0,
            "y": 2000.0,
            "properties": {
                "BehaviorType": "${MOD_NAME}",
                "IsWandering": false,
                "IsPlayerControlled": false,
                "Gender": "Male",
                "Age": 40,
                "Health": 100,
                "Cash": 5,
                "IsAlive": true,
                "DisplayHeight": 48,
                "GoalPriorities": {
                    "WANDER": 1
                },
                "ProximityRadius": 48.0,
                "InteractionRules": [],
                "ThreatNearby": false,
                "ThreatEntityId": -1,
                "ThreatEliminated": false,
                "Safe": false
            }
        },
        {
            "name": "Sample ${MOD_NAME} B",
            "type": "${MOD_NAME}",
            "x": 3400.0,
            "y": 2300.0,
            "properties": {
                "BehaviorType": "${MOD_NAME}",
                "IsWandering": false,
                "IsPlayerControlled": false,
                "Gender": "Female",
                "Age": 35,
                "Health": 100,
                "Cash": 5,
                "IsAlive": true,
                "DisplayHeight": 48,
                "GoalPriorities": {
                    "WANDER": 1
                },
                "ProximityRadius": 48.0,
                "InteractionRules": [],
                "ThreatNearby": false,
                "ThreatEntityId": -1,
                "ThreatEliminated": false,
                "Safe": false
            }
        }
    ]
}
EOF

# -- Actions/<ModName>Actions.json ---------------------------------------------

cat > "$MOD_DIR/Actions/${MOD_NAME}Actions.json" <<EOF
[
    {
        "name": "DO_WANDER",
        "preconditions": {},
        "postconditions": {
            "IsWandering": true
        },
        "cost": 1,
        "behaviorName": "${MOD_SNAKE}_DO_WANDER",
        "metadata": {
            "ExecutionAnimation": "walk_down",
            "ExecutionDuration": 1.0,
            "CompletionAnimation": "idle_down"
        }
    },
    {
        "name": "FLEE_FROM_THREAT",
        "preconditions": {
            "ThreatNearby": true
        },
        "postconditions": {
            "Safe": true
        },
        "cost": 1,
        "behaviorName": "FLEE_FROM_THREAT",
        "metadata": {
            "ExecutionAnimation": "walk_down",
            "CompletionAnimation": "idle_down"
        }
    },
    {
        "name": "ENGAGE_THREAT",
        "preconditions": {
            "ThreatNearby": true
        },
        "postconditions": {
            "ThreatEliminated": true
        },
        "cost": 1,
        "behaviorName": "ENGAGE_THREAT",
        "metadata": {
            "ExecutionAnimation": "walk_down",
            "CompletionAnimation": "idle_down"
        }
    }
]
EOF

# -- Goals/<ModName>Goals.json --------------------------------------------------

cat > "$MOD_DIR/Goals/${MOD_NAME}Goals.json" <<EOF
[
    {
        "name": "WANDER",
        "displayName": "Wandering",
        "description": "Aimlessly drifts through the area when no other goal needs attention.",
        "internal": true,
        "basePriority": 0.01,
        "desiredState": {
            "IsWandering": {
                "label": "Wandering",
                "equals": true
            }
        },
        "metadata": {
            "CompletionAnimations": [
                "idle_down",
                "idle_up"
            ],
            "CompletionDuration": 5.0,
            "CompletionDurationVariance": 3.0
        }
    },
    {
        "name": "FLEE",
        "displayName": "Flee",
        "description": "Runs away from a nearby threat at top speed. Activates automatically when a hostile gets too close.",
        "system": true,
        "basePriority": 8.0,
        "desiredState": {
            "Safe": {
                "label": "Safe",
                "equals": true
            }
        },
        "metadata": {
            "CompletionAnimations": [
                "walk_down",
                "walk_up"
            ],
            "CompletionDuration": 8.0,
            "CompletionDurationVariance": 2.0,
            "CompletionThoughtIcon": "flee_icon"
        }
    },
    {
        "name": "FIGHT",
        "displayName": "Fight",
        "description": "Engages a nearby threat. System goal - always outranks player goals.",
        "system": true,
        "basePriority": 12.0,
        "desiredState": {
            "ThreatEliminated": {
                "label": "Threat Eliminated",
                "equals": true
            }
        },
        "metadata": {
            "CompletionPauseTicks": 0,
            "CompletionAnimations": [
                "idle_down"
            ],
            "CompletionDuration": 0.5,
            "CompletionDurationVariance": 0.0
        }
    }
]
EOF

# -- Assets ----------------------------------------------------------------------

touch "$MOD_DIR/Assets/Heads/.gitkeep"
touch "$MOD_DIR/Assets/Weapons/Ranged/.gitkeep"

cat > "$MOD_DIR/Assets/Names/names.json" <<EOF
{
    "male": [
        "Alex Carter",
        "Sam Reilly",
        "Jordan Pike"
    ],
    "female": [
        "Casey Morgan",
        "Robin Shaw",
        "Taylor Quinn"
    ]
}
EOF

# -- README.md -------------------------------------------------------------------

cat > "$MOD_DIR/README.md" <<EOF
# ${MOD_NAME}

${DESCRIPTION}

This is a fully data-driven mod: no C#, no engine source edits, no rebuild
required.

\`\`\`
${MOD_NAME}/
├── mod.json                          - modId, dependencies, file lists
├── Entities/${MOD_NAME}.json         - entityType, pawnLayers, propertySchemas, instances
├── Actions/${MOD_NAME}Actions.json   - GOAP actions (DO_WANDER, FLEE_FROM_THREAT, ENGAGE_THREAT)
├── Goals/${MOD_NAME}Goals.json       - GOAP goals (WANDER, FLEE, FIGHT)
├── Assets/Heads/                     - head sprites (.png + .png.import), any size/count
├── Assets/Weapons/Ranged/            - ranged weapon sprites shown when armed
└── Assets/Names/names.json           - male/female name pools for spawned pawns
\`\`\`

## How to install

Drop this entire \`${MOD_NAME}/\` folder into the game's \`Mods/\` directory
(next to the game executable) and launch the game. The mod is discovered and
loaded automatically - no engine code changes, no rebuild.

Asset paths in \`Entities/${MOD_NAME}.json\` (\`pawnLayers.headsRoot\`,
\`pawnLayers.weaponSpritesRoot\`, \`namesRoot\`) are relative to this mod's own
folder, so it works no matter where \`Mods/\` lives on disk.

## WANDER behavior - no C# needed

Any action whose \`behaviorName\` ends in \`_DO_WANDER\` (here,
\`${MOD_SNAKE}_DO_WANDER\`) is automatically wired up to a generic wander
implementation by the engine. \`FLEE_FROM_THREAT\` and \`ENGAGE_THREAT\` are
shared, globally-registered behaviors available to every mod. Together these
cover wander/idle, flee, and basic combat with zero custom code.

## Adding content

- **Heads / weapons**: drop \`.png\` files into \`Assets/Heads\` and
  \`Assets/Weapons/Ranged\`.
- **Names**: edit \`Assets/Names/names.json\`.
- **More instances**: add entries to \`Entities/${MOD_NAME}.json\`'s
  \`"instances"\` array.
- **More goals/actions**: any goal/action that only needs \`DO_WANDER\`,
  \`FLEE_FROM_THREAT\`, or \`ENGAGE_THREAT\` behaviors works with no extra code.
  Custom behaviors beyond these require engine-side support and aren't
  available to data-only mods.
EOF

echo "  Created ${MOD_DIR}/{mod.json, Entities, Actions, Goals, Assets, README.md}"
echo ""
echo "Done. Next steps:"
echo "  1. Drop head/weapon sprites into ${MOD_DIR}/Assets/"
echo "  2. Copy ${MOD_DIR}/ into the game's Mods/ directory"
echo "  3. Launch the game and confirm ${MOD_NAME} pawns spawn and wander."
